### ISSUE TITLE
test failures with 0.4.4

### ISSUE THREAD

**Issue by loqs** [socketry/async-http-cache#10]
I have encountered multiple failures running `bake test` using ruby 3.3.5. For gem versions please [async-http-cache-0.4.4-bake-test.log](https://gist.github.com/loqs/6d48d5c910aed3bc9782661a61c9bc63) which is too long to include.

**Comment by ioquatix** [comment]
Thanks for your report, I was able to reproduce the issue and will release a fix.

**Comment by ioquatix** [comment]
I have updated the test suite to fix several issues: https://github.com/socketry/async-http-cache/commit/5c97180d4af42c7dc8003cf03a3bbb76e6da7e0d - notably the usage of `#close_write` (a recent semantic change).

I've also released v0.38.0 of `protocol-http` which fixes the usage of `Body#buffered`: https://github.com/socketry/protocol-http/commit/c60c9f8a7e134204daebd376f64a9189b046020d

Finally, I added `async-http-cache` to the external tests of `protocol-http` so this issue should be caught in the future (prevent regression): https://github.com/socketry/protocol-http/commit/5a9a061f2f8276deaa12f3674a5019f4f612a8bd

Please update `protocol-http` and your issue should be resolved.
